name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: binshadcs/booking-app-api:latest

    - name: Verify Pushed Image
      run: docker pull binshadcs/booking-app-api:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull binshadcs/booking-app-api:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --restart always --name web-app \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e PORT=${{secrets.PORT}} \
            -e DATABASE_URL=${{secrets.DATABASE_URL}} \
            -e NODE_ENV=${{secrets.development}} \
            -e ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}} \
            -e REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}} \
            -e BUCKET_NAME=${{secrets.BUCKET_NAME}} \
            -e BUCKET_REGION=${{secrets.BUCKET_REGION}} \
            -e ACCESS_KEY=${{secrets.ACCESS_KEY}} \
            -e SECRET_ACCESS_KEY=${{secrets.SECRET_ACCESS_KEY}} \
            -e REFRESH_TOKEN_EXPIRES=${{secrets.REFRESH_TOKEN_EXPIRES}} \
            -e ACCESS_TOKEN_EXPIRES=${{secrets.ACCESS_TOKEN_EXPIRES}} \
            -p 3000:3000 binshadcs/booking-app-api:latest